// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using apiprueba;

#nullable disable

namespace apiprueba.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231003035427_NewFormatDate")]
    partial class NewFormatDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("apiprueba.Models.CargosModel", b =>
                {
                    b.Property<int>("Id_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Cargo"));

                    b.Property<string>("Nombre_Cargo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(2);

                    b.HasKey("Id_Cargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("apiprueba.Models.ColaboradorModel", b =>
                {
                    b.Property<int>("Id_Colaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Colaborador"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(9);

                    b.Property<string>("CC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(6);

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnOrder(15);

                    b.Property<string>("Cargo_Colaborador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(5);

                    b.Property<string>("Cargo_Evaluador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(14);

                    b.Property<int>("Cargo_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(17);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnOrder(2);

                    b.Property<string>("Cedula_Evaluador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnOrder(11);

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(10);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnOrder(18);

                    b.Property<DateTime>("Fe_Ingreso_Colaborador")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("Fe_Ingreso_Evaluador")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnOrder(13);

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnOrder(16);

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(7);

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnOrder(3);

                    b.Property<string>("Nombres_Evaluador")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(12);

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(8);

                    b.HasKey("Id_Colaborador");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("apiprueba.Models.EvaluacionModel", b =>
                {
                    b.Property<int>("Id_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Evaluacion"));

                    b.Property<decimal?>("CalificacionFinal")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(5);

                    b.Property<decimal?>("Clfc_Pregunta1")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(6);

                    b.Property<decimal?>("Clfc_Pregunta10")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(15);

                    b.Property<decimal?>("Clfc_Pregunta11")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(16);

                    b.Property<decimal?>("Clfc_Pregunta12")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(17);

                    b.Property<decimal?>("Clfc_Pregunta13")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(18);

                    b.Property<decimal?>("Clfc_Pregunta14")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(19);

                    b.Property<decimal?>("Clfc_Pregunta15")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(20);

                    b.Property<decimal?>("Clfc_Pregunta16")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(21);

                    b.Property<decimal?>("Clfc_Pregunta17")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(22);

                    b.Property<decimal?>("Clfc_Pregunta18")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(23);

                    b.Property<decimal?>("Clfc_Pregunta19")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(24);

                    b.Property<decimal?>("Clfc_Pregunta2")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(7);

                    b.Property<decimal?>("Clfc_Pregunta20")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(25);

                    b.Property<decimal?>("Clfc_Pregunta21")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(26);

                    b.Property<decimal?>("Clfc_Pregunta22")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(27);

                    b.Property<decimal?>("Clfc_Pregunta23")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(28);

                    b.Property<decimal?>("Clfc_Pregunta24")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(29);

                    b.Property<decimal?>("Clfc_Pregunta25")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(30);

                    b.Property<decimal?>("Clfc_Pregunta26")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(31);

                    b.Property<decimal?>("Clfc_Pregunta27")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(32);

                    b.Property<decimal?>("Clfc_Pregunta28")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(33);

                    b.Property<decimal?>("Clfc_Pregunta29")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(34);

                    b.Property<decimal?>("Clfc_Pregunta3")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(8);

                    b.Property<decimal?>("Clfc_Pregunta30")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(35);

                    b.Property<decimal?>("Clfc_Pregunta31")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(36);

                    b.Property<decimal?>("Clfc_Pregunta32")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(37);

                    b.Property<decimal?>("Clfc_Pregunta33")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(38);

                    b.Property<decimal?>("Clfc_Pregunta34")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(39);

                    b.Property<decimal?>("Clfc_Pregunta35")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(40);

                    b.Property<decimal?>("Clfc_Pregunta36")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(41);

                    b.Property<decimal?>("Clfc_Pregunta37")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(42);

                    b.Property<decimal?>("Clfc_Pregunta38")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(43);

                    b.Property<decimal?>("Clfc_Pregunta39")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(44);

                    b.Property<decimal?>("Clfc_Pregunta4")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(9);

                    b.Property<decimal?>("Clfc_Pregunta40")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(45);

                    b.Property<decimal?>("Clfc_Pregunta41")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(46);

                    b.Property<decimal?>("Clfc_Pregunta42")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(47);

                    b.Property<decimal?>("Clfc_Pregunta43")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(48);

                    b.Property<decimal?>("Clfc_Pregunta44")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(49);

                    b.Property<decimal?>("Clfc_Pregunta45")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(50);

                    b.Property<decimal?>("Clfc_Pregunta46")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(51);

                    b.Property<decimal?>("Clfc_Pregunta47")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(52);

                    b.Property<decimal?>("Clfc_Pregunta48")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(53);

                    b.Property<decimal?>("Clfc_Pregunta49")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(54);

                    b.Property<decimal?>("Clfc_Pregunta5")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(10);

                    b.Property<decimal?>("Clfc_Pregunta50")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(55);

                    b.Property<decimal?>("Clfc_Pregunta51")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(56);

                    b.Property<decimal?>("Clfc_Pregunta52")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(57);

                    b.Property<decimal?>("Clfc_Pregunta6")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(11);

                    b.Property<decimal?>("Clfc_Pregunta7")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(12);

                    b.Property<decimal?>("Clfc_Pregunta8")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(13);

                    b.Property<decimal?>("Clfc_Pregunta9")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnOrder(14);

                    b.Property<int>("ColaboradorModelId_Colaborador")
                        .HasColumnType("integer");

                    b.Property<int>("Colaborador_id")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.Property<string>("Estado")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnOrder(4);

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Observacion_id")
                        .HasColumnType("integer");

                    b.Property<int>("Usuario_id")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<int>("UsuariosModelId_Usuario")
                        .HasColumnType("integer");

                    b.HasKey("Id_Evaluacion");

                    b.HasIndex("ColaboradorModelId_Colaborador");

                    b.HasIndex("UsuariosModelId_Usuario");

                    b.ToTable("Evaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.FechaProcesosEvaluacionModel", b =>
                {
                    b.Property<int>("Id_Proceso_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Proceso_Evaluacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnOrder(4);

                    b.Property<DateTimeOffset>("Fecha_Fin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(3);

                    b.Property<DateTimeOffset>("Fecha_Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(2);

                    b.HasKey("Id_Proceso_Evaluacion");

                    b.ToTable("ProcesosEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.ModuloEvaluacionModel", b =>
                {
                    b.Property<int>("Id_Modulo_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Modulo_Evaluacion"));

                    b.Property<string>("Definicion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre_Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TipoCompetenciaId_Tipo_Competencia")
                        .HasColumnType("integer");

                    b.Property<int>("TipoEvaluacionModelId_Tipo_Evaluacion")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo_Competencia_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo_Evaluacion_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id_Modulo_Evaluacion");

                    b.HasIndex("TipoCompetenciaId_Tipo_Competencia");

                    b.HasIndex("TipoEvaluacionModelId_Tipo_Evaluacion");

                    b.ToTable("ModuloEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.ObservacionModel", b =>
                {
                    b.Property<int>("Id_Observacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Observacion"));

                    b.Property<int>("Evaluacion_id")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnOrder(55);

                    b.Property<string>("Observacion1")
                        .HasColumnType("text")
                        .HasColumnOrder(3);

                    b.Property<string>("Observacion10")
                        .HasColumnType("text")
                        .HasColumnOrder(12);

                    b.Property<string>("Observacion11")
                        .HasColumnType("text")
                        .HasColumnOrder(13);

                    b.Property<string>("Observacion12")
                        .HasColumnType("text")
                        .HasColumnOrder(14);

                    b.Property<string>("Observacion13")
                        .HasColumnType("text")
                        .HasColumnOrder(15);

                    b.Property<string>("Observacion14")
                        .HasColumnType("text")
                        .HasColumnOrder(16);

                    b.Property<string>("Observacion15")
                        .HasColumnType("text")
                        .HasColumnOrder(17);

                    b.Property<string>("Observacion16")
                        .HasColumnType("text")
                        .HasColumnOrder(18);

                    b.Property<string>("Observacion17")
                        .HasColumnType("text")
                        .HasColumnOrder(19);

                    b.Property<string>("Observacion18")
                        .HasColumnType("text")
                        .HasColumnOrder(20);

                    b.Property<string>("Observacion19")
                        .HasColumnType("text")
                        .HasColumnOrder(21);

                    b.Property<string>("Observacion2")
                        .HasColumnType("text")
                        .HasColumnOrder(4);

                    b.Property<string>("Observacion20")
                        .HasColumnType("text")
                        .HasColumnOrder(22);

                    b.Property<string>("Observacion21")
                        .HasColumnType("text")
                        .HasColumnOrder(23);

                    b.Property<string>("Observacion22")
                        .HasColumnType("text")
                        .HasColumnOrder(24);

                    b.Property<string>("Observacion23")
                        .HasColumnType("text")
                        .HasColumnOrder(25);

                    b.Property<string>("Observacion24")
                        .HasColumnType("text")
                        .HasColumnOrder(26);

                    b.Property<string>("Observacion25")
                        .HasColumnType("text")
                        .HasColumnOrder(27);

                    b.Property<string>("Observacion26")
                        .HasColumnType("text")
                        .HasColumnOrder(28);

                    b.Property<string>("Observacion27")
                        .HasColumnType("text")
                        .HasColumnOrder(29);

                    b.Property<string>("Observacion28")
                        .HasColumnType("text")
                        .HasColumnOrder(30);

                    b.Property<string>("Observacion29")
                        .HasColumnType("text")
                        .HasColumnOrder(31);

                    b.Property<string>("Observacion3")
                        .HasColumnType("text")
                        .HasColumnOrder(5);

                    b.Property<string>("Observacion30")
                        .HasColumnType("text")
                        .HasColumnOrder(32);

                    b.Property<string>("Observacion31")
                        .HasColumnType("text")
                        .HasColumnOrder(33);

                    b.Property<string>("Observacion32")
                        .HasColumnType("text")
                        .HasColumnOrder(34);

                    b.Property<string>("Observacion33")
                        .HasColumnType("text")
                        .HasColumnOrder(35);

                    b.Property<string>("Observacion34")
                        .HasColumnType("text")
                        .HasColumnOrder(36);

                    b.Property<string>("Observacion35")
                        .HasColumnType("text")
                        .HasColumnOrder(37);

                    b.Property<string>("Observacion36")
                        .HasColumnType("text")
                        .HasColumnOrder(38);

                    b.Property<string>("Observacion37")
                        .HasColumnType("text")
                        .HasColumnOrder(39);

                    b.Property<string>("Observacion38")
                        .HasColumnType("text")
                        .HasColumnOrder(40);

                    b.Property<string>("Observacion39")
                        .HasColumnType("text")
                        .HasColumnOrder(41);

                    b.Property<string>("Observacion4")
                        .HasColumnType("text")
                        .HasColumnOrder(6);

                    b.Property<string>("Observacion40")
                        .HasColumnType("text")
                        .HasColumnOrder(42);

                    b.Property<string>("Observacion41")
                        .HasColumnType("text")
                        .HasColumnOrder(43);

                    b.Property<string>("Observacion42")
                        .HasColumnType("text")
                        .HasColumnOrder(44);

                    b.Property<string>("Observacion43")
                        .HasColumnType("text")
                        .HasColumnOrder(45);

                    b.Property<string>("Observacion44")
                        .HasColumnType("text")
                        .HasColumnOrder(46);

                    b.Property<string>("Observacion45")
                        .HasColumnType("text")
                        .HasColumnOrder(47);

                    b.Property<string>("Observacion46")
                        .HasColumnType("text")
                        .HasColumnOrder(48);

                    b.Property<string>("Observacion47")
                        .HasColumnType("text")
                        .HasColumnOrder(49);

                    b.Property<string>("Observacion48")
                        .HasColumnType("text")
                        .HasColumnOrder(50);

                    b.Property<string>("Observacion49")
                        .HasColumnType("text")
                        .HasColumnOrder(51);

                    b.Property<string>("Observacion5")
                        .HasColumnType("text")
                        .HasColumnOrder(7);

                    b.Property<string>("Observacion50")
                        .HasColumnType("text")
                        .HasColumnOrder(52);

                    b.Property<string>("Observacion51")
                        .HasColumnType("text")
                        .HasColumnOrder(53);

                    b.Property<string>("Observacion52")
                        .HasColumnType("text")
                        .HasColumnOrder(54);

                    b.Property<string>("Observacion6")
                        .HasColumnType("text")
                        .HasColumnOrder(8);

                    b.Property<string>("Observacion7")
                        .HasColumnType("text")
                        .HasColumnOrder(9);

                    b.Property<string>("Observacion8")
                        .HasColumnType("text")
                        .HasColumnOrder(10);

                    b.Property<string>("Observacion9")
                        .HasColumnType("text")
                        .HasColumnOrder(11);

                    b.HasKey("Id_Observacion");

                    b.HasIndex("Evaluacion_id")
                        .IsUnique();

                    b.ToTable("ObservacionEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.PreguntasByEvaluacionModel", b =>
                {
                    b.Property<int>("Id_Preguntas_Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Preguntas_Tipo"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ModuloEvaluacionModelId_Modulo_Evaluacion")
                        .HasColumnType("integer");

                    b.Property<int>("Modulo_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(4);

                    b.Property<int>("Numero_Pregunta")
                        .HasColumnType("integer")
                        .HasColumnOrder(6);

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)")
                        .HasColumnOrder(5);

                    b.Property<int>("Tipo_Evaluacion_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(3);

                    b.HasKey("Id_Preguntas_Tipo");

                    b.HasIndex("ModuloEvaluacionModelId_Modulo_Evaluacion");

                    b.HasIndex("Tipo_Evaluacion_Id");

                    b.ToTable("PreguntasByEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.PreguntasModuloCargo", b =>
                {
                    b.Property<int>("Id_PreguntaModuloCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_PreguntaModuloCargo"));

                    b.Property<int>("Cargo_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Modulo_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo_Evaluacion_Id")
                        .HasColumnType("integer");

                    b.HasKey("Id_PreguntaModuloCargo");

                    b.ToTable("PreguntasModuloCargo");
                });

            modelBuilder.Entity("apiprueba.Models.RolesModel", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Rol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("apiprueba.Models.TipoCompetenciaModel", b =>
                {
                    b.Property<int>("Id_Tipo_Competencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Tipo_Competencia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnOrder(2);

                    b.HasKey("Id_Tipo_Competencia");

                    b.ToTable("TipoCompetencia");
                });

            modelBuilder.Entity("apiprueba.Models.TipoEvaluacionModel", b =>
                {
                    b.Property<int>("Id_Tipo_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Tipo_Evaluacion"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre_Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Tipo_Evaluacion");

                    b.ToTable("Tipo_Evaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.UsuariosModel", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("integer");

                    b.Property<int>("RolesModelId_Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("RolesModelId_Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("apiprueba.Models.EvaluacionModel", b =>
                {
                    b.HasOne("apiprueba.Models.ColaboradorModel", "ColaboradorModel")
                        .WithMany("Evaluacion")
                        .HasForeignKey("ColaboradorModelId_Colaborador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiprueba.Models.UsuariosModel", "UsuariosModel")
                        .WithMany("Evaluacion")
                        .HasForeignKey("UsuariosModelId_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColaboradorModel");

                    b.Navigation("UsuariosModel");
                });

            modelBuilder.Entity("apiprueba.Models.ModuloEvaluacionModel", b =>
                {
                    b.HasOne("apiprueba.Models.TipoCompetenciaModel", "TipoCompetencia")
                        .WithMany("ModuloEvaluacion")
                        .HasForeignKey("TipoCompetenciaId_Tipo_Competencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiprueba.Models.TipoEvaluacionModel", "TipoEvaluacionModel")
                        .WithMany("ModuloEvaluacionModel")
                        .HasForeignKey("TipoEvaluacionModelId_Tipo_Evaluacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCompetencia");

                    b.Navigation("TipoEvaluacionModel");
                });

            modelBuilder.Entity("apiprueba.Models.ObservacionModel", b =>
                {
                    b.HasOne("apiprueba.Models.EvaluacionModel", "EvaluacionModel")
                        .WithOne("ObservacionModel")
                        .HasForeignKey("apiprueba.Models.ObservacionModel", "Evaluacion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluacionModel");
                });

            modelBuilder.Entity("apiprueba.Models.PreguntasByEvaluacionModel", b =>
                {
                    b.HasOne("apiprueba.Models.ModuloEvaluacionModel", "ModuloEvaluacionModel")
                        .WithMany("PreguntasByEvaluacion")
                        .HasForeignKey("ModuloEvaluacionModelId_Modulo_Evaluacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("apiprueba.Models.TipoEvaluacionModel", "TipoEvaluacionModel")
                        .WithMany("PreguntasByEvaluacionModel")
                        .HasForeignKey("Tipo_Evaluacion_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModuloEvaluacionModel");

                    b.Navigation("TipoEvaluacionModel");
                });

            modelBuilder.Entity("apiprueba.Models.UsuariosModel", b =>
                {
                    b.HasOne("apiprueba.Models.RolesModel", "RolesModel")
                        .WithMany()
                        .HasForeignKey("RolesModelId_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolesModel");
                });

            modelBuilder.Entity("apiprueba.Models.ColaboradorModel", b =>
                {
                    b.Navigation("Evaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.EvaluacionModel", b =>
                {
                    b.Navigation("ObservacionModel")
                        .IsRequired();
                });

            modelBuilder.Entity("apiprueba.Models.ModuloEvaluacionModel", b =>
                {
                    b.Navigation("PreguntasByEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.TipoCompetenciaModel", b =>
                {
                    b.Navigation("ModuloEvaluacion");
                });

            modelBuilder.Entity("apiprueba.Models.TipoEvaluacionModel", b =>
                {
                    b.Navigation("ModuloEvaluacionModel");

                    b.Navigation("PreguntasByEvaluacionModel");
                });

            modelBuilder.Entity("apiprueba.Models.UsuariosModel", b =>
                {
                    b.Navigation("Evaluacion");
                });
#pragma warning restore 612, 618
        }
    }
}
